# DuV-Termin2-NumPy-Dateien

## 4.4 Dateiein- und -ausgabe bei Arrays

NumPy ist in der Lage, Daten sowohl im **Text- als auch im Binärformat** auf der Festplatte zu **speichern** und von ihr zu **laden**.<br>
- in NumPy eingebaute Binärformat<br>

**np.save** und **np.load** sind die zwei Arbeitspferde zum effizienten Speichern und Laden von Array-Daten auf und von der Platte. Arrays werden standardmäßig in einem unkomprimierten rohen Binärformat mit der Dateierweiterung .npy gespeichert:<br>

In [6]:
import numpy as np
NpArr10 = np.arange(10)
NpArr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.save('some_array', NpArr10)
# Sollte der Dateipfad noch nicht auf .npy enden, wird die Erweiterung angehängt
!dir *.np*

 Datentr„ger in Laufwerk C: ist Local Disk
 Volumeseriennummer: 82EE-7974

 Verzeichnis von C:\Users\micha\ki-studium\Datenanalyse und Visualisierung\DuV-Termin-02

02.03.2023  14:53               168 some_array.npy
               1 Datei(en),            168 Bytes
               0 Verzeichnis(se), 344.452.456.448 Bytes frei


In [15]:
some_other_array = np.load('some_array.npy')
some_other_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Zum Speichern mehrerer Arrays in einem unkomprimierten Archiv nutzen Sie np.savez 
# und übergeben die Arrays als Schlüsselwortargumente
np.savez('array_archive.npz', a=NpArr10, b=some_other_array*2)
!dir *.np*

 Datentr„ger in Laufwerk C: ist Local Disk
 Volumeseriennummer: 82EE-7974

 Verzeichnis von C:\Users\micha\ki-studium\Datenanalyse und Visualisierung\DuV-Termin-02

02.03.2023  14:55               570 array_archive.npz
02.03.2023  14:53               168 some_array.npy
               2 Datei(en),            738 Bytes
               0 Verzeichnis(se), 344.454.504.448 Bytes frei


In [23]:
arch = np.load('array_archive.npz')
print(arch['a'])
print(arch['b'])

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
# Lassen sich Ihre Daten gut komprimieren, könnten Sie stattdessen numpy.savez_compressed benutzen
np.savez_compressed('array_compressed.npz', a=NpArr10*2, b=some_other_array**2)
!dir *.np*

 Datentr„ger in Laufwerk C: ist Local Disk
 Volumeseriennummer: 82EE-7974

 Verzeichnis von C:\Users\micha\ki-studium\Datenanalyse und Visualisierung\DuV-Termin-02

02.03.2023  14:55               570 array_archive.npz
02.03.2023  14:59               422 array_compressed.npz
02.03.2023  14:53               168 some_array.npy
               3 Datei(en),          1.160 Bytes
               0 Verzeichnis(se), 344.456.921.088 Bytes frei


In [26]:
arch = np.load('array_compressed.npz')
print(arch['a'])
print(arch['b'])

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
